### PR TITLE
Fixing rafael/test-1-test-issue

### PR DESCRIPTION
**Pull request by rkabesa**

### CODE REVIEW

**Review by rkabesa — COMMENTED** [review]
reviewed rkabesa-patch-3

**Review by swilliamsdf18 — CHANGES_REQUESTED** [review]
reviewing

**Review by swilliamsdf18 — COMMENTED** [review]
reviewing rkabesa-patch-3

**Review by swilliamsdf18 — APPROVED** [review]
approved

**Review by swilliamsdf18 — CHANGES_REQUESTED** [review]
update TEST-1

**Review by swilliamsdf18 — APPROVED** [review]

**Pull request merged**
